# ch01_시작하며

---
## 1.3 Introduction to Python and Pandas
---

### 1.3.1 Arithmetic Operations: Python as a Calculator

In [1]:
5+3

8

In [2]:
5-3

2

In [3]:
5/3

1.6666666666666667

In [4]:
5&3

1

In [5]:
5%3

2

In [6]:
5**3

125

In [7]:
5 * (10 - 3)

35

In [8]:
from math import sqrt

In [9]:
sqrt(4)

2.0

### 1.3.2: Modules and Packages

In [10]:
import math

In [11]:
math.sqrt(4)

2.0

In [12]:
math.log(1)

0.0

In [13]:
import pandas as pd

### 1.3.3: Python Script

In [ ]:
'''
This is the start of a Python script
The heading provides some information about the file

File name: testing_arithmetic.py
Author: <Your Name>
Date created: <Date>
Purpose: Practicing basic math commands and commenting in Python
'''

5-3 # What is 5 mi
5/3
5**3 
5*(10-3) # A bit more complex

# This function returns the square root of a number
math.sqrt(4)

2.0

### 1.3.4: Variables and Object

In [16]:
result = 5 + 3
result

8

In [17]:
print(result)

8

In [18]:
result = 5 - 3
print(result)

2

In [19]:
kosuke = 'instructor'
kosuke

'instructor'

In [20]:
kosuke = 'instructor and author'
kosuke

'instructor and author'

In [21]:
Result = '5'
Result

'5'

In [22]:
result

2

In [23]:
result+=5
result

7

In [24]:
type(result)

int

In [25]:
type(Result)

str

In [26]:
type(math.sqrt)

builtin_function_or_method

### 1.3.4: Python Data Structures: Lists, Dictionaries, Tuples, Set

List

In [1]:
world_pop = [2525779, 3026003, 3691173, 4449049, 5320817, 6127700, 6916183]
world_pop

[2525779, 3026003, 3691173, 4449049, 5320817, 6127700, 6916183]

In [28]:
pop_first = world_pop[:3]
pop_second = world_pop[3:]
pop_all = pop_first + pop_second
pop_all

[2525779, 3026003, 3691173, 4449049, 5320817, 6127700, 6916183]

In [29]:
world_pop[0]

2525779

In [30]:
world_pop[1]

3026003

In [31]:
world_pop[-1]

6916183

In [32]:
world_pop[:4]

[2525779, 3026003, 3691173, 4449049]

In [33]:
len(world_pop)

7

In [34]:
world_pop[4:]

[5320817, 6127700, 6916183]

In [35]:
list(range(1950, 2011, 10))

[1950, 1960, 1970, 1980, 1990, 2000, 2010]

In [36]:
mixed_list = [10, 10.5, True, 'USA', 'Canada']
mixed_list

[10, 10.5, True, 'USA', 'Canada']

In [37]:
mixed_list[4] = 'Mexico'
mixed_list

[10, 10.5, True, 'USA', 'Mexico']

In [38]:
mixed_list.append('Canada')
mixed_list

[10, 10.5, True, 'USA', 'Mexico', 'Canada']

In [39]:
alt_list = mixed_list
alt_list

[10, 10.5, True, 'USA', 'Mexico', 'Canada']

In [40]:
mixed_list.append('USA')
mixed_list

[10, 10.5, True, 'USA', 'Mexico', 'Canada', 'USA']

In [41]:
alt_list

[10, 10.5, True, 'USA', 'Mexico', 'Canada', 'USA']

In [42]:
alt_list = mixed_list.copy()
alt_list

[10, 10.5, True, 'USA', 'Mexico', 'Canada', 'USA']

In [43]:
mixed_list.append(10)
mixed_list

[10, 10.5, True, 'USA', 'Mexico', 'Canada', 'USA', 10]

In [44]:
alt_list

[10, 10.5, True, 'USA', 'Mexico', 'Canada', 'USA']

In [45]:
world_pop

[2525779, 3026003, 3691173, 4449049, 5320817, 6127700, 6916183]

In [46]:
world_pop * 2

[2525779,
 3026003,
 3691173,
 4449049,
 5320817,
 6127700,
 6916183,
 2525779,
 3026003,
 3691173,
 4449049,
 5320817,
 6127700,
 6916183]

In [47]:
2525779 / 1000

2525.779

In [48]:
pop_million = [pop / 1000 for pop in world_pop]
pop_million

[2525.779, 3026.003, 3691.173, 4449.049, 5320.817, 6127.7, 6916.183]

In [49]:
[item for item in mixed_list if isinstance(item, str)]

['USA', 'Mexico', 'Canada', 'USA']

Dictionary

In [11]:
world_pop_dict = {'1950': 2525779, '1960': 3026003, '1970': 3691173, 
                  '1980': 4449049, '1990': 5320817, '2000': 6127700}

world_pop_dict

{'1950': 2525779,
 '1960': 3026003,
 '1970': 3691173,
 '1980': 4449049,
 '1990': 5320817,
 '2000': 6127700}

In [51]:
world_pop_dict['1990']

5320817

In [52]:
world_pop_dict['2010'] = 6916183
world_pop_dict

{'1950': 2525779,
 '1960': 3026003,
 '1970': 3691173,
 '1980': 4449049,
 '1990': 5320817,
 '2000': 6127700,
 '2010': 6916183}

In [53]:
world_pop_dict.keys()

dict_keys(['1950', '1960', '1970', '1980', '1990', '2000', '2010'])

In [54]:
world_pop_dict.values()

dict_values([2525779, 3026003, 3691173, 4449049, 5320817, 6127700, 6916183])

In [55]:
list(world_pop_dict.values())

[2525779, 3026003, 3691173, 4449049, 5320817, 6127700, 6916183]

In [57]:
list(world_pop_dict.items())

[('1950', 2525779),
 ('1960', 3026003),
 ('1970', 3691173),
 ('1980', 4449049),
 ('1990', 5320817),
 ('2000', 6127700),
 ('2010', 6916183)]

Tuple

In [58]:
world_pop_t = (2525779, 3026003, 3691173, 4449049, 5320817, 6127700, 6916183)
world_pop_t

(2525779, 3026003, 3691173, 4449049, 5320817, 6127700, 6916183)

In [59]:
world_pop_t[0]

2525779

In [60]:
world_pop_t[4:]

(5320817, 6127700, 6916183)

In [73]:
try:
    world_pop_t[2] = 100
except Exception as e:
    print(repr(e))

TypeError("'tuple' object does not support item assignment")

Set

In [74]:
print(mixed_list)

[10, 10.5, True, 'USA', 'Mexico', 'Canada', 'USA', 10]

In [75]:
set(mixed_list)

{10, 10.5, 'Canada', 'Mexico', True, 'USA'}

### 1.3.5: Pandas Data Structures: Series and DataFrames

Series

In [2]:
import pandas as pd

In [3]:
world_pop_s = pd.Series(world_pop)
world_pop_s

0    2525779
1    3026003
2    3691173
3    4449049
4    5320817
5    6127700
6    6916183
dtype: int64

In [4]:
world_pop_s[1]

np.int64(3026003)

In [6]:
world_pop_s[:4]

0    2525779
1    3026003
2    3691173
3    4449049
dtype: int64

In [7]:
world_pop_s[[0,2]]

0    2525779
2    3691173
dtype: int64

In [8]:
world_pop_s.drop(2)

0    2525779
1    3026003
3    4449049
4    5320817
5    6127700
6    6916183
dtype: int64

In [9]:
world_pop_s[:-1]

0    2525779
1    3026003
2    3691173
3    4449049
4    5320817
5    6127700
dtype: int64

In [12]:
world_pop_s2 = pd.Series(world_pop_dict)
world_pop_s2

1950    2525779
1960    3026003
1970    3691173
1980    4449049
1990    5320817
2000    6127700
dtype: int64

In [14]:
world_pop_s2['1990']

np.int64(5320817)

In [15]:
pop_million = world_pop_s / 1000
pop_million

0    2525.779
1    3026.003
2    3691.173
3    4449.049
4    5320.817
5    6127.700
6    6916.183
dtype: float64

In [16]:
pop_rate = world_pop_s / world_pop_s[0]
pop_rate

0    1.000000
1    1.198047
2    1.461400
3    1.761456
4    2.106604
5    2.426063
6    2.738238
dtype: float64

In [23]:
pop_increase = (
    world_pop_s.drop(0).reset_index(drop=True) - 
    world_pop_s.drop(6).reset_index(drop=True)
)

pop_increase

0    500224
1    665170
2    757876
3    871768
4    806883
5    788483
dtype: int64

In [24]:
percent_increase = pop_increase / world_pop_s.drop(6) * 100
percent_increase

0    19.804741
1    21.981802
2    20.532118
3    19.594480
4    15.164645
5    12.867520
dtype: float64

In [27]:
world_pop_s.pct_change() * 100

0          NaN
1    19.804741
2    21.981802
3    20.532118
4    19.594480
5    15.164645
6    12.867520
dtype: float64

In [28]:
percent_increase

0    19.804741
1    21.981802
2    20.532118
3    19.594480
4    15.164645
5    12.867520
dtype: float64

In [29]:
percent_increase[[0,1]] = [20, 22]
percent_increase

0    20.000000
1    22.000000
2    20.532118
3    19.594480
4    15.164645
5    12.867520
dtype: float64

DataFrame

In [31]:
world_pop_df = pd.DataFrame(
    {
        'year': list(range(1950, 2011, 10)),
        'pop': world_pop
    }
)

world_pop_df

   year      pop
0  1950  2525779
1  1960  3026003
2  1970  3691173
3  1980  4449049
4  1990  5320817
5  2000  6127700
6  2010  6916183

In [32]:
world_pop_df.columns

Index(['year', 'pop'], dtype='str')

In [33]:
world_pop_df.shape

(7, 2)

In [34]:
world_pop_df.describe()

              year           pop
count     7.000000  7.000000e+00
mean   1980.000000  4.579529e+06
std      21.602469  1.625004e+06
min    1950.000000  2.525779e+06
25%    1965.000000  3.358588e+06
50%    1980.000000  4.449049e+06
75%    1995.000000  5.724258e+06
max    2010.000000  6.916183e+06

In [35]:
world_pop_df.describe().astype(int)

       year      pop
count     7        7
mean   1980  4579529
std      21  1625003
min    1950  2525779
25%    1965  3358588
50%    1980  4449049
75%    1995  5724258
max    2010  6916183

In [36]:
world_pop_df['pop']

0    2525779
1    3026003
2    3691173
3    4449049
4    5320817
5    6127700
6    6916183
Name: pop, dtype: int64

In [37]:
world_pop_df[:3]

   year      pop
0  1950  2525779
1  1960  3026003
2  1970  3691173

In [38]:
world_pop_df.loc[:2, ['pop','year']]

       pop  year
0  2525779  1950
1  3026003  1960
2  3691173  1970

In [39]:
world_pop_df.iloc[:3, [1,0]]

       pop  year
0  2525779  1950
1  3026003  1960
2  3691173  1970

In [41]:
world_pop_df['pop'][::2]

0    2525779
2    3691173
4    5320817
6    6916183
Name: pop, dtype: int64

In [42]:
import numpy as np

In [44]:
world_pop = pd.concat([world_pop_df['pop'], pd.Series([np.nan])], ignore_index=True)
world_pop

0    2525779.0
1    3026003.0
2    3691173.0
3    4449049.0
4    5320817.0
5    6127700.0
6    6916183.0
7          NaN
dtype: float64

In [45]:
world_pop.mean().round(2)

np.float64(4579529.14)

In [46]:
world_pop.mean(skipna=False)

np.float64(nan)

### 1.3.6: Functions and Methods

In [47]:
world_pop = world_pop_df['pop']
world_pop

0    2525779
1    3026003
2    3691173
3    4449049
4    5320817
5    6127700
6    6916183
Name: pop, dtype: int64

In [48]:
len(world_pop)

7

In [49]:
world_pop.min()

np.int64(2525779)

In [50]:
world_pop.max()

np.int64(6916183)

In [51]:
world_pop.mean()

np.float64(4579529.142857143)

In [53]:
world_pop.mean().round(2)

np.float64(4579529.14)

In [54]:
world_pop.sum() / len(world_pop)

np.float64(4579529.142857143)

In [55]:
year = np.arange(1950, 2011, 10)
year

array([1950, 1960, 1970, 1980, 1990, 2000, 2010])

In [56]:
np.arange(start=1950, step=10, stop=2011)

array([1950, 1960, 1970, 1980, 1990, 2000, 2010])

In [57]:
pd.Series(np.arange(2010, 1949, -10))

0    2010
1    2000
2    1990
3    1980
4    1970
5    1960
6    1950
dtype: int64

In [58]:
world_pop.index

RangeIndex(start=0, stop=7, step=1)

In [59]:
year

array([1950, 1960, 1970, 1980, 1990, 2000, 2010])

In [60]:
world_pop.index = year
world_pop.index

Index([1950, 1960, 1970, 1980, 1990, 2000, 2010], dtype='int64')

In [61]:
world_pop

1950    2525779
1960    3026003
1970    3691173
1980    4449049
1990    5320817
2000    6127700
2010    6916183
Name: pop, dtype: int64

In [62]:
'''
def myfunction(input1, input2, ..., inputN):
    DEFINE `output` USING INPUTS
    return output
'''

def my_summary(x): # function takes one input
    s_out = x.sum()
    l_out = len(x)
    m_out = x.mean()
    out = pd.Series([s_out, l_out, m_out], index = ['sum', 'length', 'mean'])
    return out # end function by calling output

In [63]:
z = np.arange(1,11)
my_summary(z)

sum       55.0
length    10.0
mean       5.5
dtype: float64

In [64]:
my_summary(world_pop).astype(int)

sum       32056704
length           7
mean       4579529
dtype: int64

In [65]:
type(my_summary)

function

In [66]:
type(np.arange)

builtin_function_or_method

### 1.3.7: Loading and Saving Data

In [67]:
import os

In [68]:
os.getcwd()

'/home/user/repo/studies/qss'

In [69]:
os.chdir('/home/user/repo/studies/qss/data')

In [70]:
un_pop = pd.read_csv('UNpop.csv')
un_pop

   year  world_pop
0  1950    2525779
1  1960    3026003
2  1970    3691173
3  1980    4449049
4  1990    5320817
5  2000    6127700
6  2010    6916183

In [71]:
un_pop.to_pickle('UNpop.pkl')