# CH02_인과효과

---
## 2.1 노동시장에서 인종차별
---

```
Bertrand, Marianne, and Sendhil Mullainathan. 2004. "Are Emily and Greg More Employable Than Lakisha and Jamal? A Field Experiment on Labor Market Discrimination." American Economic Review 94 (4): 991–1013.
DOI: 10.1257/0002828042002561

In [1]:
import numpy as np
import pandas as pd

In [2]:
resume = pd.read_csv('data/resume.csv')

In [3]:
resume.shape

(4870, 4)

In [4]:
resume.head(6)

  firstname     sex   race  call
0   Allison  female  white     0
1   Kristen  female  white     0
2   Lakisha  female  black     0
3   Latonya  female  black     0
4    Carrie  female  white     0
5       Jay    male  white     0

In [5]:
resume.dtypes

firstname      str
sex            str
race           str
call         int64
dtype: object

In [8]:
resume.describe()

              call
count  4870.000000
mean      0.080493
std       0.272083
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000

In [14]:
for col in resume.columns[:3]:
    print(resume[col].value_counts())
    print()

firstname
Tamika      256
Anne        242
Allison     232
Latonya     230
Emily       227
Latoya      226
Kristen     213
Ebony       208
Tanisha     207
Jill        203
Lakisha     200
Kenya       196
Laurie      195
Sarah       193
Meredith    187
Keisha      183
Aisha       180
Carrie      168
Neil         76
Tyrone       75
Tremayne     69
Todd         68
Jay          67
Matthew      67
Rasheed      67
Brendan      65
Leroy        64
Kareem       64
Brad         63
Jamal        61
Geoffrey     59
Brett        59
Hakim        55
Jermaine     52
Greg         51
Darnell      42
Name: count, dtype: int64

sex
female    3746
male      1124
Name: count, dtype: int64

race
white    2435
black    2435
Name: count, dtype: int64

In [15]:
race_call_tab = pd.crosstab(resume.race, resume.call)
race_call_tab

call      0    1
race
black  2278  157
white  2200  235

In [16]:
pd.crosstab(resume.race, resume.call, margins=True)

call      0    1   All
race
black  2278  157  2435
white  2200  235  2435
All    4478  392  4870

In [19]:
race_call_tab.iloc[:,1].sum() / resume.shape[0]

np.float64(0.08049281314168377)

In [20]:
race_call_tab.loc['black', 1] / race_call_tab.loc['black'].sum()

np.float64(0.06447638603696099)

In [21]:
race_call_tab.loc['white', 1] / race_call_tab.loc['white'].sum()

np.float64(0.09650924024640657)

In [23]:
race_call_tab.iloc[0]

call
0    2278
1     157
Name: black, dtype: int64

In [25]:
race_call_tab.iloc[:, 1]

race
black    157
white    235
Name: 1, dtype: int64

In [26]:
(race_call_tab.loc['white', 1] / race_call_tab.loc['white'].sum()) - (race_call_tab.loc['black', 1] / race_call_tab.loc['black'].sum())

np.float64(0.032032854209445585)

In [27]:
resume['call'].mean()

np.float64(0.08049281314168377)

---
## 2.2 데이터 부분 선택
---

### 2.2.1: Boolean Values and Logical Operat

In [28]:
type(True)

bool

In [29]:
int(True)

1

In [30]:
int(False)

0

In [33]:
x = pd.Series([True, False, True])
x.mean().round(2)

np.float64(0.67)

In [35]:
x.sum()

np.int64(2)

In [36]:
False & True

False

In [37]:
True | False

True

In [38]:
False | False

False

In [39]:
True & False & True

False

In [40]:
(True | False) & False

False

In [41]:
True | (False & False)

True

In [42]:
TF1 = pd.Series([True, False, False])
TF2 = pd.Series([True, False, True])
TF1 | TF2

0     True
1    False
2     True
dtype: bool

In [43]:
TF1 & TF2

0     True
1    False
2    False
dtype: bool

### 2.2.2: Relational Operators

In [44]:
4 > 3

True

In [45]:
'Hello' == 'hello'

False

In [46]:
'Hello' != 'hello'

True

In [47]:
x = pd.Series([3,2,1,-2,-1])
x >= 2

0     True
1     True
2    False
3    False
4    False
dtype: bool

In [49]:
x != 1

0     True
1     True
2    False
3     True
4     True
dtype: bool

In [51]:
(x > 0) & (x <= 2)

0    False
1     True
2     True
3    False
4    False
dtype: bool

In [52]:
(x > 2) | (x <= -1)

0     True
1    False
2    False
3     True
4     True
dtype: bool

In [53]:
x_int = (x > 0) & (x <= 2)
x_int

0    False
1     True
2     True
3    False
4    False
dtype: bool

In [54]:
x_int.mean()

np.float64(0.4)

In [55]:
x_int.sum()

np.int64(2)

### 2.2.3: Subsetting

In [56]:
resume['call'][resume['race'] == 'black'].mean()

np.float64(0.06447638603696099)

In [58]:
resume['race'][:5]

0    white
1    white
2    black
3    black
4    white
Name: race, dtype: str

In [57]:
resume['race'][:5] == 'black'

0    False
1    False
2     True
3     True
4    False
Name: race, dtype: bool

In [59]:
resume.shape

(4870, 4)

In [60]:
resumeB = resume.loc[resume['race'] == 'black'].copy()
resumeB.shape

(2435, 4)

In [61]:
resumeB['call'].mean()

np.float64(0.06447638603696099)

In [62]:
resumeBf = (
    resume.loc[(resume.race == 'black') & (resume.sex == 'female'), ['call', 'firstname']]
)

resumeBf.head(6)

    call firstname
2      0   Lakisha
3      0   Latonya
7      0     Kenya
8      0   Latonya
10     0     Aisha
12     0     Aisha

In [64]:
resumeBf = resume.loc[(resume.race == 'black') & (resume.sex == 'female')]
resumeBm = resume.loc[(resume.race == 'black') & (resume.sex == 'male')]
resumeWf = resume.loc[(resume.race == 'white') & (resume.sex == 'female')]
resumeWm = resume.loc[(resume.race == 'white') & (resume.sex == 'male')]

In [65]:
resumeWf['call'].mean() - resumeBf['call'].mean()

np.float64(0.0326468944913853)

In [66]:
resumeWm['call'].mean() - resumeBm['call'].mean()

np.float64(0.03040785618119901)

### 2.2.4: Simple Conditional Statements

In [67]:
resume['BlackFemale'] = (
    np.where(
        (resume.race == 'black') & (resume.sex == 'female'), 1, 0
    )
)

In [69]:
resume.head()

  firstname     sex   race  call  BlackFemale
0   Allison  female  white     0            0
1   Kristen  female  white     0            0
2   Lakisha  female  black     0            1
3   Latonya  female  black     0            1
4    Carrie  female  white     0            0

In [72]:
pd.crosstab([resume.race, resume.sex], resume.BlackFemale)

BlackFemale      0     1
race  sex
black female     0  1886
      male     549     0
white female  1860     0
      male     575     0

In [73]:
resume.drop('BlackFemale', axis=1, inplace=True)

### 2.2.5: Categorical Variables

In [74]:
cat_vars = ['firstname', 'sex', 'race']

resume[cat_vars] = resume[cat_vars].astype('category')
resume.dtypes

firstname    category
sex          category
race         category
call            int64
dtype: object

In [75]:
resume['race'][:5]

0    white
1    white
2    black
3    black
4    white
Name: race, dtype: category
Categories (2, str): ['black', 'white']

In [76]:
resume['race'].cat.categories

Index(['black', 'white'], dtype='str')

In [77]:
resume['race'].cat.codes

0       1
1       1
2       0
3       0
4       1
       ..
4865    0
4866    0
4867    1
4868    0
4869    1
Length: 4870, dtype: int8

In [78]:
resume['race'].value_counts()

race
black    2435
white    2435
Name: count, dtype: int64

In [79]:
resume['race'].value_counts(normalize=True)

race
black    0.5
white    0.5
Name: proportion, dtype: float64

In [81]:
resume[cat_vars].describe()

       firstname     sex   race
count       4870    4870   4870
unique        36       2      2
top       Tamika  female  black
freq         256    3746   2435

In [82]:
resume.describe(include='all')

       firstname     sex   race         call
count       4870    4870   4870  4870.000000
unique        36       2      2          NaN
top       Tamika  female  black          NaN
freq         256    3746   2435          NaN
mean         NaN     NaN    NaN     0.080493
std          NaN     NaN    NaN     0.272083
min          NaN     NaN    NaN     0.000000
25%          NaN     NaN    NaN     0.000000
50%          NaN     NaN    NaN     0.000000
75%          NaN     NaN    NaN     0.000000
max          NaN     NaN    NaN     1.000000

In [83]:
resume['type'] = ''
(resume.loc[(resume.race == 'black') & (resume.sex == 'female'), 'type']) = 'BlackFemale'
(resume.loc[(resume.race == 'black') & (resume.sex == 'male'), 'type']) = 'BlackMale'
(resume.loc[(resume.race == 'white') & (resume.sex == 'female'), 'type']) = 'WhiteFemale'
(resume.loc[(resume.race == 'white') & (resume.sex == 'male'), 'type']) = 'WhiteMale'

In [85]:
resume.dtypes

firstname    category
sex          category
race         category
call            int64
type              str
dtype: object

In [90]:
resume['type'].value_counts().index

Index(['BlackFemale', 'WhiteFemale', 'WhiteMale', 'BlackMale'], dtype='str', name='type')

In [92]:
conditions = [
    (resume.race == 'black') & (resume.sex == 'female'),
    (resume.race == 'black') & (resume.sex == 'male'),
    (resume.race == 'white') & (resume.sex == 'female')
]

choices = ['BlackFemale', 'BlackMale', 'WhiteFemale']

resume['type_alt'] = np.select(conditions, choices, 'WhiteMale')

resume['type'].equals(resume['type_alt'])

True

In [93]:
resume.drop('type_alt', axis=1, inplace=True)
resume.dtypes

firstname    category
sex          category
race         category
call            int64
type              str
dtype: object

In [94]:
resume['type'] = resume['type'].astype('category')
resume['type'].cat.categories

Index(['BlackFemale', 'BlackMale', 'WhiteFemale', 'WhiteMale'], dtype='str')

In [95]:
resume['type'].value_counts(sort=False)

type
BlackFemale    1886
BlackMale       549
WhiteFemale    1860
WhiteMale       575
Name: count, dtype: int64

In [97]:
resume.groupby('type')['call'].mean()

type
BlackFemale    0.066278
BlackMale      0.058288
WhiteFemale    0.098925
WhiteMale      0.088696
Name: call, dtype: float64

In [100]:
callback_name = resume.groupby('firstname')['call'].mean()
callback_name.sort_values().head(10)

firstname
Aisha       0.022222
Rasheed     0.029851
Keisha      0.038251
Tremayne    0.043478
Kareem      0.046875
Darnell     0.047619
Tyrone      0.053333
Hakim       0.054545
Tamika      0.054688
Lakisha     0.055000
Name: call, dtype: float64

In [101]:
callback_name.sort_values(ascending=False).head(10)

firstname
Brad        0.158730
Jay         0.134328
Kristen     0.131455
Carrie      0.130952
Meredith    0.101604
Sarah       0.098446
Laurie      0.097436
Jermaine    0.096154
Ebony       0.096154
Allison     0.094828
Name: call, dtype: float64

---
## 2.3 인과효과와 반사실
---

In [108]:
resume[:1]

  firstname     sex   race  call         type
0   Allison  female  white     0  WhiteFemale

In [111]:
resume.iloc[0]

firstname        Allison
sex               female
race               white
call                   0
type         WhiteFemale
Name: 0, dtype: object

---
## 2.4 무작위 대조시험
---

### 2.4.1 무작위의 역할

### 2.4.2 사회적 압박과 투표율

```
GERBER, A. S., GREEN, D. P., & LARIMER, C. W. (2008). Social Pressure and Voter Turnout: Evidence from a Large-Scale Field Experiment. American Political Science Review, 102(1), 33–48. doi:10.1017/S000305540808009X

In [5]:
import os
import pandas as pd
import numpy as np

In [2]:
os.getcwd()

'/home/user/repo/studies/qss'

In [3]:
os.chdir('/home/user/repo/studies/qss/data')
os.getcwd()

'/home/user/repo/studies/qss/data'

In [6]:
social = pd.read_csv('social.csv')
social.describe().round(2)

       yearofbirth  primary2004  primary2006     hhsize
count    305866.00    305866.00    305866.00  305866.00
mean       1956.21         0.40         0.31       2.18
std          14.45         0.49         0.46       0.79
min        1900.00         0.00         0.00       1.00
25%        1947.00         0.00         0.00       2.00
50%        1956.00         0.00         0.00       2.00
75%        1965.00         1.00         1.00       2.00
max        1986.00         1.00         1.00       8.00

In [7]:
social.info()

<class 'pandas.DataFrame'>
RangeIndex: 305866 entries, 0 to 305865
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   sex          305866 non-null  str
 1   yearofbirth  305866 non-null  int64
 2   primary2004  305866 non-null  int64
 3   messages     305866 non-null  str
 4   primary2006  305866 non-null  int64
 5   hhsize       305866 non-null  int64
dtypes: int64(4), str(2)
memory usage: 14.0 MB

In [8]:
social[['sex', 'messages']] = social[['sex', 'messages']].astype('category')
social['messages'].cat.categories

Index(['Civic Duty', 'Control', 'Hawthorne', 'Neighbors'], dtype='str')

In [9]:
social['messages']

0         Civic Duty
1         Civic Duty
2          Hawthorne
3          Hawthorne
4          Hawthorne
             ...
305861       Control
305862       Control
305863       Control
305864       Control
305865       Control
Name: messages, Length: 305866, dtype: category
Categories (4, str): ['Civic Duty', 'Control', 'Hawthorne', 'Neighbors']

In [10]:
social['messages'] = social['messages'].cat.reorder_categories(['Control', 'Civic Duty', 'Hawthorne', 'Neighbors'])
social['messages'].cat.categories

Index(['Control', 'Civic Duty', 'Hawthorne', 'Neighbors'], dtype='str')

In [11]:
social['messages'].cat.codes

0         1
1         1
2         2
3         2
4         2
         ..
305861    0
305862    0
305863    0
305864    0
305865    0
Length: 305866, dtype: int8

In [12]:
social['messages'].cat.ordered

False

In [13]:
social.groupby('messages')['primary2006'].mean()

messages
Control       0.296638
Civic Duty    0.314538
Hawthorne     0.322375
Neighbors     0.377948
Name: primary2006, dtype: float64

In [14]:
social['primary2006'][social.messages == 'Control'].mean()

np.float64(0.2966383083302395)

In [15]:
social.loc[:, 'primary2006'][social.messages == 'Control'].mean()

np.float64(0.2966383083302395)

In [16]:
(social.groupby('messages')['primary2006'].mean() - social['primary2006'][social.messages == 'Control'].mean())

messages
Control       0.000000
Civic Duty    0.017899
Hawthorne     0.025736
Neighbors     0.081310
Name: primary2006, dtype: float64

In [17]:
social['age'] = 2006 - social['yearofbirth']
social.groupby('messages')['age'].mean()

messages
Control       49.813546
Civic Duty    49.659035
Hawthorne     49.704795
Neighbors     49.852936
Name: age, dtype: float64

In [18]:
social.groupby('messages')['primary2004'].mean()

messages
Control       0.400339
Civic Duty    0.399445
Hawthorne     0.403230
Neighbors     0.406665
Name: primary2004, dtype: float64

In [19]:
social.groupby('messages')['hhsize'].mean()

messages
Control       2.183667
Civic Duty    2.189126
Hawthorne     2.180138
Neighbors     2.187770
Name: hhsize, dtype: float64

---
## 2.5 관찰연구
---

### 2.5.1. 최저임금과 실업률

```
Card, David, and Alan B. Krueger. 2000. "Minimum Wages and Employment: A Case Study of the Fast-Food Industry in New Jersey and Pennsylvania: Reply." American Economic Review 90 (5): 1397–1420.
DOI: 10.1257/aer.90.5.1397

In [35]:
minwage = pd.read_csv('minwage.csv', dtype={'chain':'category', 'location':'category'})
minwage.info()

<class 'pandas.DataFrame'>
RangeIndex: 358 entries, 0 to 357
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   chain       358 non-null    category
 1   location    358 non-null    category
 2   wageBefore  358 non-null    float64
 3   wageAfter   358 non-null    float64
 4   fullBefore  358 non-null    float64
 5   fullAfter   358 non-null    float64
 6   partBefore  358 non-null    float64
 7   partAfter   358 non-null    float64
dtypes: category(2), float64(6)
memory usage: 17.8 KB

In [36]:
minwage.shape

(358, 8)

In [37]:
minwage.describe().round(2)

       wageBefore  wageAfter  fullBefore  fullAfter  partBefore  partAfter
count      358.00     358.00      358.00     358.00      358.00     358.00
mean         4.62       4.99        8.47       8.36       18.75      18.69
std          0.35       0.26        8.70       7.81       10.29      10.57
min          4.25       4.25        0.00       0.00        0.00       0.00
25%          4.25       5.05        2.12       2.00       11.00      11.00
50%          4.50       5.05        6.00       6.00       16.25      17.00
75%          4.99       5.05       12.00      12.00       25.00      25.00
max          5.75       6.25       60.00      40.00       60.00      60.00

In [38]:
minwage['chain'].value_counts()

chain
burgerking    149
roys           88
kfc            75
wendys         46
Name: count, dtype: int64

In [39]:
minwage['location'].value_counts()

location
northNJ      146
PA            67
southNJ       67
centralNJ     45
shoreNJ       33
Name: count, dtype: int64

In [40]:
minwage.select_dtypes(include='category').columns

Index(['chain', 'location'], dtype='str')

In [41]:
minwageNJ = minwage.loc[minwage.location != 'PA'].copy()
minwagePA = minwage.loc[minwage.location == 'PA'].copy()

In [42]:
(minwageNJ['wageBefore'] < 5.05).mean()

np.float64(0.9106529209621993)

In [43]:
(minwageNJ['wageAfter'] < 5.05).mean()

np.float64(0.003436426116838488)

In [44]:
(minwagePA['wageBefore'] < 5.05).mean()

np.float64(0.9402985074626866)

In [45]:
(minwagePA['wageAfter'] < 5.05).mean()

np.float64(0.9552238805970149)

In [48]:
minwageNJ['fullPropAfter'] = (
    minwageNJ['fullAfter'] / (minwageNJ['fullAfter'] + minwageNJ.partAfter)
)

minwagePA['fullPropAfter'] = (
    minwagePA.fullAfter / (minwagePA.fullAfter + minwagePA.partAfter)
)

minwageNJ['fullPropAfter'].mean() - minwagePA['fullPropAfter'].mean()

np.float64(0.04811886142291416)

### 2.5.2 중첩편향

In [52]:
minwageNJ['chain'].value_counts(sort=False, normalize=True)

chain
burgerking    0.405498
kfc           0.223368
roys          0.250859
wendys        0.120275
Name: proportion, dtype: float64

In [53]:
minwagePA['chain'].value_counts(sort=False, normalize=True)

chain
burgerking    0.462687
kfc           0.149254
roys          0.223881
wendys        0.164179
Name: proportion, dtype: float64

In [54]:
minwageNJ_bk = minwageNJ.loc[minwageNJ.chain == 'burgerking'].copy()
minwagePA_bk = minwagePA.loc[minwagePA.chain == 'burgerking'].copy()

minwageNJ_bk['fullPropAfter'].mean() - minwagePA_bk['fullPropAfter'].mean()

np.float64(0.03643933939149829)

In [55]:
minwageNJ_bk_subset = (
    minwageNJ_bk.loc[(minwageNJ_bk.location != 'shoreNJ') & (minwageNJ_bk.location != 'centralNJ')].copy()
)

minwageNJ_bk_subset['fullPropAfter'].mean() - minwagePA_bk['fullPropAfter'].mean()

np.float64(0.031498534750908636)

### 2.5.3 전후비교법 및 이중차분법 설계

In [56]:
minwageNJ['fullPropBefore'] = (
    minwageNJ['fullBefore'] / (minwageNJ.fullBefore + minwageNJ.partBefore)
)

NJdiff = minwageNJ.fullPropAfter.mean() - minwageNJ.fullPropBefore.mean()
NJdiff

np.float64(0.0238747402131399)

In [57]:
minwagePA['fullPropBefore'] = (
    minwagePA['fullBefore'] / (minwagePA.fullBefore + minwagePA.partBefore)
)

PAdiff = minwagePA.fullPropAfter.mean() - minwagePA.fullPropBefore.mean()

NJdiff - PAdiff

np.float64(0.06155831231224712)

---
## 2.6 단일 변수의 기술통계량
---

### 2.6.1 분위수

In [58]:
minwageNJ.fullPropAfter.median() - minwagePA.fullPropAfter.median()

np.float64(0.07291666666666669)

In [59]:
NJdiff_med = (minwageNJ.fullPropAfter.median() - minwageNJ.fullPropBefore.median())
NJdiff_med

np.float64(0.025000000000000022)

In [61]:
PAdiff_med = (minwagePA.fullPropAfter.median() - minwagePA.fullPropBefore.median())
NJdiff_med - PAdiff_med

np.float64(0.037019230769230804)

In [62]:
minwageNJ['wageBefore'].describe().round(2)

count    291.00
mean       4.61
std        0.34
min        4.25
25%        4.25
50%        4.50
75%        4.87
max        5.75
Name: wageBefore, dtype: float64

In [63]:
minwageNJ['wageAfter'].describe().round(2)

count    291.00
mean       5.08
std        0.11
min        5.00
25%        5.05
50%        5.05
75%        5.05
max        5.75
Name: wageAfter, dtype: float64

In [65]:
(minwageNJ['wageBefore'].quantile(0.75) - minwageNJ['wageBefore'].quantile(0.25)).round(2)

np.float64(0.62)

In [66]:
(minwageNJ['wageAfter'].quantile(0.75) - minwageNJ['wageAfter'].quantile(0.25)).round(2)

np.float64(0.0)

In [67]:
minwageNJ['wageBefore'].quantile(np.arange(0, 1.1, 0.1))

0.0    4.25
0.1    4.25
0.2    4.25
0.3    4.25
0.4    4.50
0.5    4.50
0.6    4.65
0.7    4.75
0.8    5.00
0.9    5.00
1.0    5.75
Name: wageBefore, dtype: float64

In [68]:
minwageNJ['wageAfter'].quantile(np.arange(0, 1.1, 0.1))

0.0    5.00
0.1    5.05
0.2    5.05
0.3    5.05
0.4    5.05
0.5    5.05
0.6    5.05
0.7    5.05
0.8    5.05
0.9    5.15
1.0    5.75
Name: wageAfter, dtype: float64

### 2.6.2 표준편차

In [75]:
np.sqrt((minwageNJ.fullPropAfter - minwageNJ.fullPropBefore).pow(2).mean())

np.float64(0.3014668578470611)

In [76]:
(minwageNJ.fullPropAfter - minwageNJ.fullPropBefore).mean()

np.float64(0.023874740213139886)

In [77]:
minwageNJ['fullPropBefore'].std()

np.float64(0.23045922465419544)

In [78]:
minwageNJ['fullPropAfter'].std()

np.float64(0.25100159189283716)

In [79]:
minwageNJ['fullPropBefore'].var()

np.float64(0.053111454228212916)

In [80]:
minwageNJ['fullPropAfter'].var()

np.float64(0.06300179913273839)

---
## 2.8 연습문제
---

### 2.8.1 초기 교육에서 소규모 학습 효용

```
Mosteller, F. (1995). The Tennessee study of class size in the early school grades. The Future of Children, 5(2), 113–127.
https://doi.org/10.2307/1602360

In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
os.chdir('/home/user/repo/studies/qss/data')

In [3]:
star = pd.read_csv('STAR.csv')

In [4]:
star.head()

   race  classtype  yearssmall  hsgrad  g4math  g4reading
0   1.0          3           0     NaN     NaN        NaN
1   2.0          3           0     NaN   706.0      661.0
2   1.0          3           0     1.0   711.0      750.0
3   2.0          1           4     NaN   672.0      659.0
4   1.0          2           0     NaN     NaN        NaN

In [5]:
star.info()

<class 'pandas.DataFrame'>
RangeIndex: 6325 entries, 0 to 6324
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   race        6322 non-null   float64
 1   classtype   6325 non-null   int64
 2   yearssmall  6325 non-null   int64
 3   hsgrad      3047 non-null   float64
 4   g4math      2395 non-null   float64
 5   g4reading   2353 non-null   float64
dtypes: float64(4), int64(2)
memory usage: 296.6 KB

In [6]:
star.describe()

,race,classtype,yearssmall,hsgrad,g4math,g4reading
count,6322.000000,6325.000000,6325.000000,3047.000000,2395.000000,2353.000000
mean,1.340715,2.052332,0.954150,0.833279,708.776618,721.247769
std,0.515861,0.806528,1.458833,0.372788,43.092174,52.425922
min,1.000000,1.000000,0.000000,0.000000,487.000000,528.000000
25%,1.000000,1.000000,0.000000,1.000000,688.000000,696.000000
50%,1.000000,2.000000,0.000000,1.000000,710.000000,723.000000
75%,2.000000,3.000000,2.000000,1.000000,732.500000,750.000000
max,6.000000,3.000000,4.000000,1.000000,821.000000,836.000000

Q1

In [7]:
classtype_map = {1: 'small', 2: 'regular', 3: 'regular_with_aid'}
star['kinder'] = star.classtype.map(classtype_map).astype('category')

In [8]:
star.head()

   race  classtype  yearssmall  hsgrad  g4math  g4reading            kinder
0   1.0          3           0     NaN     NaN        NaN  regular_with_aid
1   2.0          3           0     NaN   706.0      661.0  regular_with_aid
2   1.0          3           0     1.0   711.0      750.0  regular_with_aid
3   2.0          1           4     NaN   672.0      659.0             small
4   1.0          2           0     NaN     NaN        NaN           regular

In [11]:
race_map = {
    1:'white',
    2:'black',
    3:'others',
    4: 'hispanic',
    5: 'others',
    6: 'others'
}

star['race'] = star['race'].map(race_map).astype('category')

In [12]:
star.head()

    race  classtype  yearssmall  hsgrad  g4math  g4reading            kinder
0  white          3           0     NaN     NaN        NaN  regular_with_aid
1  black          3           0     NaN   706.0      661.0  regular_with_aid
2  white          3           0     1.0   711.0      750.0  regular_with_aid
3  black          1           4     NaN   672.0      659.0             small
4  white          2           0     NaN     NaN        NaN           regular

In [13]:
star.info()

<class 'pandas.DataFrame'>
RangeIndex: 6325 entries, 0 to 6324
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   race        6322 non-null   category
 1   classtype   6325 non-null   int64
 2   yearssmall  6325 non-null   int64
 3   hsgrad      3047 non-null   float64
 4   g4math      2395 non-null   float64
 5   g4reading   2353 non-null   float64
 6   kinder      6325 non-null   category
dtypes: category(2), float64(3), int64(2)
memory usage: 259.6 KB

In [16]:
star['kinder'].value_counts(dropna=False)

kinder
regular_with_aid    2231
regular             2194
small               1900
Name: count, dtype: int64

In [17]:
star['race'].value_counts(dropna=False)

race
white       4234
black       2058
others        25
hispanic       5
NaN            3
Name: count, dtype: int64

Q2

In [28]:
diff = star.loc[star['kinder'] == 'small', ['g4math', 'g4reading']].mean() - star.loc[star['kinder'] == 'regular', ['g4math', 'g4reading']].mean()
diff

g4math      -0.336243
g4reading    3.501232
dtype: float64

In [29]:
sd = star[['g4math', 'g4reading']].std()
sd

g4math       43.092174
g4reading    52.425922
dtype: float64

In [30]:
effect_size = diff / sd
effect_size

g4math      -0.007803
g4reading    0.066784
dtype: float64

Q3

In [34]:
star.loc[star['kinder'] == 'small', ['g4math', 'g4reading']].quantile([.66, .33])

      g4math  g4reading
0.66   726.0      741.0
0.33   694.0      705.0

In [35]:
star.loc[star['kinder'] == 'regular', ['g4math', 'g4reading']].quantile([.66, .33])

      g4math  g4reading
0.66   724.0      740.0
0.33   696.0      705.0

In [36]:
star.loc[star['kinder'] == 'small', ['g4math', 'g4reading']].quantile([.66, .33]) - star.loc[star['kinder'] == 'regular', ['g4math', 'g4reading']].quantile([.66, .33])

      g4math  g4reading
0.66     2.0        1.0
0.33    -2.0        0.0

Q4

In [37]:
pd.crosstab(star.kinder, star.yearssmall)

yearssmall           0    1    2    3    4
kinder
regular           1961   95   58   80    0
regular_with_aid  1996   97   60   78    0
small                0  576  272  195  857

In [45]:
pd.crosstab(star.kinder, star.yearssmall, normalize=True)

yearssmall               0         1         2         3         4
kinder
regular           0.310040  0.015020  0.009170  0.012648  0.000000
regular_with_aid  0.315573  0.015336  0.009486  0.012332  0.000000
small             0.000000  0.091067  0.043004  0.030830  0.135494

In [43]:
star.groupby(['kinder', 'yearssmall'])[['g4math', 'g4reading']].mean()

                                 g4math   g4reading
kinder           yearssmall
regular          0           708.767606  718.958924
                 1           706.181818  726.878788
                 2           716.973684  715.777778
                 3           715.459016  729.311475
regular_with_aid 0           707.169320  720.835312
                 1           713.970588  717.757576
                 2           714.147059  730.764706
                 3           705.481481  714.220000
small            1           703.000000  724.666667
                 2           699.142857  700.571429
                 3           704.500000  709.148148
                 4           710.051908  724.665109

In [44]:
star.groupby(['kinder', 'yearssmall'])[['g4math', 'g4reading']].median()

                             g4math  g4reading
kinder           yearssmall
regular          0            710.0      722.0
                 1            696.0      730.0
                 2            714.0      723.0
                 3            714.0      727.0
regular_with_aid 0            710.0      722.0
                 1            715.0      715.0
                 2            714.0      720.5
                 3            710.0      720.5
small            1            706.0      724.5
                 2            712.0      711.0
                 3            707.0      707.0
                 4            711.0      726.0

In [46]:
star.groupby('yearssmall')[['g4math', 'g4reading']].mean()

                g4math   g4reading
yearssmall
0           707.979300  719.875362
1           707.552381  723.147059
2           711.913978  717.868132
3           709.617021  719.898551
4           710.051908  724.665109

In [47]:
star.groupby('yearssmall')[['g4math', 'g4reading']].median()

            g4math  g4reading
yearssmall
0            710.0      722.0
1            709.0      724.5
2            714.0      720.0
3            712.0      721.0
4            711.0      726.0

Q5

In [59]:
race_group_map = {'white': 'white', 'black': 'minority', 'hispanic': 'minority'}
star['race_group'] = star['race'].map(race_group_map)
star['race_group'].value_counts(dropna=False)

race_group
white       4234
minority    2063
NaN           28
Name: count, dtype: int64

In [67]:
regular_scores = star.loc[
    (star['kinder'] == 'regular') & star['race_group'].notna(), ['race_group', 'g4math', 'g4reading']
].groupby('race_group').mean()

regular_scores

                g4math   g4reading
race_group
minority    698.532258  689.354839
white       711.410364  725.115819

In [69]:
small_scores = star.loc[
    (star['kinder'] == 'small') & star['race_group'].notna(), ['race_group', 'g4math', 'g4reading']
].groupby('race_group').mean()

small_scores

                g4math   g4reading
race_group
minority    698.222222  699.284483
white       711.190016  727.838816

In [71]:
regular_scores.loc['white'] - regular_scores.loc['minority']

g4math       12.878106
g4reading    35.760980
dtype: float64

In [72]:
small_scores.loc['white'] - small_scores.loc['minority']

g4math       12.967794
g4reading    28.554333
dtype: float64

Q6

In [78]:
star.groupby('kinder')['hsgrad'].mean()

kinder
regular             0.825162
regular_with_aid    0.839286
small               0.835920
Name: hsgrad, dtype: float64

In [79]:
star.groupby('yearssmall')['hsgrad'].mean()

yearssmall
0    0.828602
1    0.791045
2    0.813187
3    0.832461
4    0.877551
Name: hsgrad, dtype: float64

In [83]:
regular_hsgrad = star.loc[
    (star['kinder'] == 'regular') & star['race_group'].notna(), ['race_group', 'hsgrad']
].groupby('race_group').mean()

regular_hsgrad

              hsgrad
race_group
minority    0.739583
white       0.856962

In [84]:
small_hsgrad = star.loc[
    (star['kinder'] == 'small') & star['race_group'].notna(), ['race_group', 'hsgrad']
].groupby('race_group').mean()

small_hsgrad

              hsgrad
race_group
minority    0.744681
white       0.867470

In [87]:
regular_hsgrad.loc['white'] - regular_hsgrad.loc['minority']

hsgrad    0.117379
dtype: float64

In [88]:
small_hsgrad.loc['white'] - small_hsgrad.loc['minority']

hsgrad    0.122789
dtype: float64